### ISSUE TITLE
subscription "Display amount" isn't doing it

### ISSUE THREAD

**Issue by mdagit** [New0/direct-stripe#107]
While displaying the amount for a one-time payment is done in the button, it doesn't
seem to work for a subscription. It doesn't show any amount.

**Comment by New0** [comment]
Hello @mdagit ,

This is not a feature of Direct Stripe at the moment, the display amount option works for payment and donation types of buttons. I will add it to the description of the button.

Technically, the pricing plan ID is used during the subscription process and is not retrieved before the Stripe modal form opened, that means we don't have the amount of the pricing plan available at that point. 
In order to show the amount in the form for subscription types of buttons,  we need to retrieve the plan before the Direct Stripe button is clicked, that is not a feature I plan to add. I hope you'll understand it doesn't fit the generic use of the plugin and should remain a custom development for the people that really need it. 

Also, the amount can also be mentioned in the description or the title of the Stripe's form ;-)
