### ISSUE TITLE
Support for trial period on subscription

### ISSUE THREAD

**Issue by richardkmiller** [New0/direct-stripe#77]
Hi, thanks for building Direct Stripe! 

Can I ask you to add support for a trial period on a subscription?

I created a plan with a trial period in the Stripe dashboard, but it didn't work with Direct Stripe. When I made a test purchase, the subscription did not have the trial period. Stripe Support told me the API call to `\Stripe\Subscription::create` needs to set `trial_from_plan=true`.

Alternatively, Direct Stripe can ask the user for the length of the trial in days, and then pass `trial_period_days=n` or `trial_end=unix_timestamp`. 

Thanks for your help!

**Comment by New0** [comment]
Hello @richardkmiller , thank you for using Direct Stripe.

I'm sorry for the late reply, I am working on an add-on to manage Stripe subscriptions and pricing plans but as it is a side project I can't promise any timelapse for release...

This comment also makes me realize I'm poorly documenting on Direct Stripe and I apologize about that.

There are actions and filters that allow to extend and use extended Stripe options. In this case, the filter that allows you to set trial_from_plan=true is not documented because it is missing arguments like button_id (which is usefull to target only one button) and I considered it wasn't ready... https://newo.me/direct-stripe-actions-and-filters-hooks/.

But I think you can set trial_from_plan for all subscription buttons and don't need to target one precise button in this case so I made a gist of how to use it at https://gist.github.com/New0/b414230c89c7cc3028c7e498957e4bad

Let me know if you need help using the code.

Best wishes !

**Comment by Benmidi** [comment]
Hello @New0,

Thanks for providing that gist, I would love some instruction on using it as I don't work with WordPress or PHP often.

**Comment by New0** [comment]
Hello @Benmidi 

I'd be glad to help you use that gist. 
As I mentioned previously, when using actions or filters it is better to target a precise button ( and that filter is not ready for that ), but in that case the code won't have effect on pricing plans that don't have a trial period set.

The best way to use that code is installing it as a custom plugin
- On the gist page ( https://gist.github.com/New0/b414230c89c7cc3028c7e498957e4bad ), click the Download zip button
- On the WordPress interface, go to the Plugins -> Add new
- Click the Upload Plugin button and select the Zip file previously downloaded
- Activate the plugin

Run tests !

Another way, in the case you use a custom or child-theme, you can copy/paste the code in the functions.php file of the theme. 

Let me know how that goes and if you have other questions.

**Comment by richardkmiller** [comment]
Thanks @New0, I didn't know about the actions and filters for Direct Stripe. That's really helpful!

In theory, it would be nice to have `button_id` because we have 6 different buttons, but in reality, only 1-2 buttons are associated with plans with a trial, so I think for us it will be harmless to set `trial_from_plan=true` on all the plans. 

I'll let you know how it goes! Thanks for your response!

**Comment by Benmidi** [comment]
Thanks @New0!

**Comment by New0** [comment]
Hello @richardkmiller , @Benmidi 

I wanted to let you know that I added the $button_ID argument for the filter hook in the last update to 2.1.6.
It's now documented at https://newo.me/direct-stripe-actions-and-filters-hooks/

Best wishes !

**Comment by richardkmiller** [comment]
@New0 Thank you! I really appreciate it! We will use it.
